#!/usr/bin/env bash
[ -z "$DEBUG" ] || set -x
set -eo pipefail

[ -n "$PLATFORMS" ] || PLATFORMS="linux/amd64,linux/arm64/v8"
[ -n "$PLATFORM" ] || PLATFORM="--platform=$PLATFORMS"

[ -z "$REGISTRY" ] || PREFIX="$REGISTRY/"

SOURCE_COMMIT=$(git rev-parse --verify HEAD 2>/dev/null || echo '')
if [[ ! -z "$SOURCE_COMMIT" ]]; then
  GIT_STATUS=$(git status --untracked-files=normal --porcelain=v2 | grep -v ' hooks/build' || true)
  if [[ ! -z "$GIT_STATUS" ]]; then
    SOURCE_COMMIT="$SOURCE_COMMIT-dirty"
  fi
fi

MULTIARCH_NONROOT="
builder-base
builder-base-gcc
builder-base-gcloud
builder-tooling
builder-node
builder-quarkus
git-init
toil
toil-network
node-distroless
blobs
"

MULTIARCH_TONONROOT="
java
node
node-kafka
node-kafka-cache
node-watchexec
node-gcloud
runtime-quarkus-ubuntu
runtime-quarkus-ubuntu-jre
runtime-quarkus-dev
toil-storage
"

AMD64ONLY="
runtime-quarkus
runtime-quarkus-deno
runtime-deno
git-http-readonly
headless-chrome
"

ACTIONS="./actions-generated.yaml"
echo "    # generated by $0 for manual copy-paste to images.yaml" > $ACTIONS

function base_action {
  CONTEXT=$1
  NAME=$2
  TAG=$3
  TAGSUFFIX=""
  [ "$TAG" = "latest" ] || TAGSUFFIX="-$TAG"
  cat <<EOF
    -
      name: Build and push $NAME $TAG
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: $CONTEXT
        tags: |
          ghcr.io/yolean/$NAME:$TAG
          ghcr.io/yolean/$NAME:\${{ github.sha }}$TAGSUFFIX
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
EOF
}

function add_dependencies {
  CONTEXT=$1
  DEPENDENCIES="$((grep -e 'FROM --platform=$TARGETPLATFORM yolean/' $CONTEXT/Dockerfile || true) | cut -d' ' -f3)"
  [ -z "$DEPENDENCIES" ] || echo "        build-contexts: |"
  for NAME in $DEPENDENCIES; do
    echo "          $NAME=docker-image://ghcr.io/$NAME"
  done
}

for CONTEXT in $MULTIARCH_NONROOT; do
  base_action "$CONTEXT" "$CONTEXT" latest >> $ACTIONS
  add_dependencies "$CONTEXT" >> $ACTIONS
done

for CONTEXT in $MULTIARCH_TONONROOT; do
  mkdir -p to-nonroot/$CONTEXT
  echo "FROM --platform=\$TARGETPLATFORM yolean/$CONTEXT:root" > to-nonroot/$CONTEXT/Dockerfile
  cat nonroot-footer.Dockerfile >> to-nonroot/$CONTEXT/Dockerfile
  base_action "$CONTEXT" "$CONTEXT" root >> $ACTIONS
  add_dependencies "$CONTEXT" >> $ACTIONS
  base_action "to-nonroot/$CONTEXT" "$CONTEXT" latest >> $ACTIONS
done

for CONTEXT in $AMD64ONLY; do
  echo "# TODO does $CONTEXT really need to be amd64-only?" >&2
done
