# Before we go wild with this FROM we might want to await a debian with https://github.com/debuerreotype/debuerreotype/releases/tag/0.3
FROM debian:stretch-slim@sha256:b4c6e46603728bdc550c9075be78439c45a0d509008770ad3775d097f28b6cca
