# Before we go wild with this FROM we might want to await a debian with https://github.com/debuerreotype/debuerreotype/releases/tag/0.3
FROM debian:stretch-slim@sha256:3a5c99d91859cdaa02b971427c02b916ad823f98720014145ee4f8fc01d7c140
