# Before we go wild with this FROM we might want to await a debian with https://github.com/debuerreotype/debuerreotype/releases/tag/0.3
FROM debian:stretch-slim@sha256:ee1b82157527a9d2d5a5e96b2033ad69ba831058a9bd71288a217b5a1c970553
