#!/bin/bash
set -e

[ -z "$IMAGE_NAME" ] && echo "IMAGE_NAME is required" && exit 1;

function imagename {
  buildname=$1
  case $IMAGE_NAME in
    *:latest) echo -n $IMAGE_NAME | sed "s|:latest|:$buildname|" ;;
    *:*) echo -n $IMAGE_NAME | sed "s|:\(.*\)|:\1-$buildname|" ;;
    *) echo $IMAGE_NAME:$buildname ;;
  esac
}

if [ "$YOLEAN_PROMOTE" != "true" ]; then
  docker build -t $IMAGE_NAME .
else
  YOLEAN_PROMOTE_TAG="$(curl -L 'https://hub.docker.com/api/audit/v1/build/?include_related=true&offset=0&limit=10&object=%2Fapi%2Frepo%2Fv1%2Frepository%2Fsolsson%2Fy-docker-base%2F' | jq -r '.objects[0].commit')"
  echo "Latest build's git ref is $YOLEAN_PROMOTE_TAG, right?"
  read -p "Verified? [y/n] " ok && [ "$ok" = "y" ] || exit 1
fi

CONTEXTS="
java
node
node-kafka
node-kafka-cache
toil
builder-base
builder-java
builder-node
builder-quarkus
"

# Hack so we can get node-kafka-cache on Node 10.x as well (gracefulfs legacy)
case $IMAGE_NAME in
  *:node10)
    sed -i 's/FROM node:.*/FROM node:10.21.0-buster-slim@sha256:ab8807ef49075f6f10b56b2442b09fb45f959938958817d737b3e69cdfa5323d/' node/Dockerfile
    CONTEXTS="node node-kafka node-kafka-cache"
    ;;
esac

PUSH=""

for CONTEXT in $CONTEXTS; do

  CONTEXT_IMAGE_NAME=$(imagename $CONTEXT)

  docker build -t yolean/$CONTEXT \
    -t yolean/$CONTEXT:$SOURCE_COMMIT-root \
    -t $CONTEXT_IMAGE_NAME-root ./$CONTEXT
  cat ./$CONTEXT/Dockerfile ./nonroot-footer.Dockerfile | \
    docker build -f - \
    -t yolean/$CONTEXT:$SOURCE_COMMIT \
    -t $CONTEXT_IMAGE_NAME ./$CONTEXT
  PUSH="$PUSH $CONTEXT_IMAGE_NAME $CONTEXT_IMAGE_NAME-root"
  PUSH="$PUSH yolean/$CONTEXT:$SOURCE_COMMIT yolean/$CONTEXT:$SOURCE_COMMIT-root"

done

echo "PUSH list contains: $PUSH"
[ -z "$NOPUSH" ] || exit 0
for P in $PUSH; do docker push $P; done
