#!/usr/bin/env bash
[ -z "$DEBUG" ] || set -x
set -eo pipefail

[ -z "$IMAGE_NAME" ] && echo "IMAGE_NAME is required" && exit 1;

[ -n "$PLATFORM" ] || PLATFORM="--platform=linux/amd64,linux/arm64/v8"

function imagename {
  buildname=$1
  case $IMAGE_NAME in
    *:latest) echo -n $IMAGE_NAME | sed "s|:latest|:$buildname|" ;;
    *:*) echo -n $IMAGE_NAME | sed "s|:\(.*\)|:\1-$buildname|" ;;
    *) echo $IMAGE_NAME:$buildname ;;
  esac
}

MULTIARCH_NONROOT="
builder-base
builder-base-gcc
builder-tooling
builder-node
toil
"

MULTIARCH_TONONROOT="
java
node
node-kafka
node-kafka-cache
"

AMD64ONLY="
git-init
builder-quarkus
builder-quarkus-mvncache
runtime-quarkus
runtime-quarkus-ubuntu
runtime-quarkus-ubuntu-jre
runtime-quarkus-dev
runtime-quarkus-deno
runtime-deno
git-http-readonly
"

XTAG=""

[ -n "$NOPUSH" ] || BUILDX_PUSH="--push"

cat ./Dockerfile | \
  docker buildx build $BUILDX_PUSH --progress=plain $PLATFORM \
  -t $IMAGE_NAME -

for CONTEXT in $MULTIARCH_NONROOT; do
  CONTEXT_IMAGE_NAME=$(imagename $CONTEXT)

  cat ./$CONTEXT/Dockerfile | \
    docker buildx build $BUILDX_PUSH --progress=plain $PLATFORM -f - \
    -t yolean/$CONTEXT:$SOURCE_COMMIT$XTAG \
    -t $CONTEXT_IMAGE_NAME ./$CONTEXT
done

for CONTEXT in $MULTIARCH_TONONROOT; do
  CONTEXT_IMAGE_NAME=$(imagename $CONTEXT)

  cat ./$CONTEXT/Dockerfile ./nonroot-footer.Dockerfile | \
    docker buildx build $BUILDX_PUSH --progress=plain $PLATFORM -f - \
    -t yolean/$CONTEXT:$SOURCE_COMMIT$XTAG \
    -t $CONTEXT_IMAGE_NAME ./$CONTEXT
done

PUSH=""

for CONTEXT in $AMD64ONLY; do
  CONTEXT_IMAGE_NAME=$(imagename $CONTEXT)

  docker build -t yolean/$CONTEXT \
    -t yolean/$CONTEXT:$SOURCE_COMMIT$XTAG \
    -t $CONTEXT_IMAGE_NAME ./$CONTEXT
  PUSH="$PUSH yolean/$CONTEXT:$SOURCE_COMMIT$XTAG $CONTEXT_IMAGE_NAME"
  if [ "" = "$(docker image inspect -f='{{.Config.User}}' $CONTEXT_IMAGE_NAME)" ]; then
    docker tag $CONTEXT_IMAGE_NAME $CONTEXT_IMAGE_NAME-root
    docker tag yolean/$CONTEXT:$SOURCE_COMMIT$XTAG yolean/$CONTEXT:$SOURCE_COMMIT$XTAG-root
    PUSH="$PUSH yolean/$CONTEXT:$SOURCE_COMMIT$XTAG-root $CONTEXT_IMAGE_NAME-root"
    cat ./$CONTEXT/Dockerfile ./nonroot-footer.Dockerfile | \
      docker build -f - \
      -t yolean/$CONTEXT:$SOURCE_COMMIT$XTAG \
      -t $CONTEXT_IMAGE_NAME ./$CONTEXT
  fi
done

echo "amd64-only PUSH list contains: $PUSH"
[ -z "$NOPUSH" ] || exit 0
for P in $PUSH; do docker push $P; done
