#!/bin/bash
set -e

docker build -t $IMAGE_NAME .

for CONTEXT in "
    node
    node-kafka
  "; do
  
  CONTEXT_IMAGE_NAME=$(echo -n $IMAGE_NAME | sed "s|:|:$CONTEXT-|")

  docker build -t $CONTEXT_IMAGE_NAME ./$CONTEXT
  docker push $CONTEXT_IMAGE_NAME
done
