FROM --platform=$TARGETPLATFORM gcr.io/distroless/nodejs18-debian11:nonroot@sha256:d914bfbbec77a75a6fb1767b9329b0af5e770fbdb6cd9bec2ba351c1264d9759

WORKDIR /app
CMD [ "--enable-source-maps", "./main.js" ]
