name: ci

# Found no convenient way to configure public access
# on:
#   push:
#     branches:
#     - ghcr

# Note: below was a test, does not support our nonroot append that ./hooks/build does

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: builder-base
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/yolean/builder-base:latest
          ghcr.io/yolean/builder-base:${{ github.sha }}
