name: images

on:
  push:
    branches:
    - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    -
      uses: imjasonh/setup-crane@v0.3
    -
      run: |
        TAG_KKV=7fa31f42731fc20a77988b478a3896732cc3dc88
        TAG_HOOK=76984f89554bd8b2beadb086edc998cc36ab381c
        TAG_KAFKA=2.5.1-kafka-server-start
        TAG_ZOOKEEPER=2.5.1-zookeeper-server-start
        TAG_INITUTILS=initutils-nonroot@sha256:8988aca5b34feabe8d7d4e368f74b2ede398f692c7e99a38b262a938d475812c
        crane cp docker.io/yolean/kafka-keyvalue:$TAG_KKV ghcr.io/yolean/kafka-keyvalue:$TAG_KKV
        crane cp docker.io/yolean/kafka-hook:$TAG_HOOK ghcr.io/yolean/kafka-hook:$TAG_HOOK
        crane cp solsson/kafka:$TAG_KAFKA ghcr.io/yolean/kafka:$TAG_KAFKA
        crane cp solsson/kafka:$TAG_ZOOKEEPER ghcr.io/yolean/kafka:$TAG_ZOOKEEPER
        crane cp solsson/kafka:$TAG_INITUTILS ghcr.io/yolean/kafka:$TAG_INITUTILS
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    ### build steps below are generated ###
    -
      name: Build and push node-kafka-watch root
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: node-kafka-watch
        tags: |
          ghcr.io/yolean/node-kafka-watch:root
          ghcr.io/yolean/node-kafka-watch:${{ github.sha }}-root
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/node-watchexec:root=docker-image://ghcr.io/yolean/node-watchexec:root
          yolean/node-kafka:root=docker-image://ghcr.io/yolean/node-kafka:root
    -
      name: Build and push node-kafka-watch latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: to-nonroot/node-kafka-watch
        tags: |
          ghcr.io/yolean/node-kafka-watch:latest
          ghcr.io/yolean/node-kafka-watch:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/node-kafka-watch:root=docker-image://ghcr.io/yolean/node-kafka-watch:root
