name: images

on:
  push:
    branches:
    - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    -
      uses: imjasonh/setup-crane@v0.3
    -
      run: |
        TAG_KKV=7fa31f42731fc20a77988b478a3896732cc3dc88
        TAG_HOOK=76984f89554bd8b2beadb086edc998cc36ab381c
        TAG_KAFKA=2.5.1-kafka-server-start
        TAG_ZOOKEEPER=2.5.1-zookeeper-server-start
        crane cp docker.io/yolean/kafka-keyvalue:$TAG_KKV ghcr.io/yolean/kafka-keyvalue:$TAG_KKV
        crane cp docker.io/yolean/kafka-hook:$TAG_HOOK ghcr.io/yolean/kafka-hook:$TAG_HOOK
        crane cp solsson/kafka:$TAG_KAFKA ghcr.io/yolean/kafka:$TAG_KAFKA
        crane cp solsson/kafka:$TAG_ZOOKEEPER ghcr.io/yolean/kafka:$TAG_ZOOKEEPER
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    ### build steps below are generated ###
    -
      name: Build and push headless-chrome latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: headless-chrome
        tags: |
          ghcr.io/yolean/headless-chrome:latest
          ghcr.io/yolean/headless-chrome:${{ github.sha }}
        platforms: linux/amd64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/docker-base=docker-image://ghcr.io/yolean/docker-base
    -
      name: Build and push git-http-readonly latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: git-http-readonly
        tags: |
          ghcr.io/yolean/git-http-readonly:latest
          ghcr.io/yolean/git-http-readonly:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push runtime-quarkus latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: runtime-quarkus
        tags: |
          ghcr.io/yolean/runtime-quarkus:latest
          ghcr.io/yolean/runtime-quarkus:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push java root
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: java
        tags: |
          ghcr.io/yolean/java:root
          ghcr.io/yolean/java:${{ github.sha }}-root
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push java latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: to-nonroot/java
        tags: |
          ghcr.io/yolean/java:latest
          ghcr.io/yolean/java:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/java:root=docker-image://ghcr.io/yolean/java:root
    -
      name: Build and push runtime-quarkus-ubuntu root
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: runtime-quarkus-ubuntu
        tags: |
          ghcr.io/yolean/runtime-quarkus-ubuntu:root
          ghcr.io/yolean/runtime-quarkus-ubuntu:${{ github.sha }}-root
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/docker-base=docker-image://ghcr.io/yolean/docker-base
    -
      name: Build and push runtime-quarkus-ubuntu latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: to-nonroot/runtime-quarkus-ubuntu
        tags: |
          ghcr.io/yolean/runtime-quarkus-ubuntu:latest
          ghcr.io/yolean/runtime-quarkus-ubuntu:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/runtime-quarkus-ubuntu:root=docker-image://ghcr.io/yolean/runtime-quarkus-ubuntu:root
    -
      name: Build and push runtime-quarkus-ubuntu-jre root
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: runtime-quarkus-ubuntu-jre
        tags: |
          ghcr.io/yolean/runtime-quarkus-ubuntu-jre:root
          ghcr.io/yolean/runtime-quarkus-ubuntu-jre:${{ github.sha }}-root
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/java:root=docker-image://ghcr.io/yolean/java:root
          yolean/runtime-quarkus-ubuntu:root=docker-image://ghcr.io/yolean/runtime-quarkus-ubuntu:root
    -
      name: Build and push runtime-quarkus-ubuntu-jre latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: to-nonroot/runtime-quarkus-ubuntu-jre
        tags: |
          ghcr.io/yolean/runtime-quarkus-ubuntu-jre:latest
          ghcr.io/yolean/runtime-quarkus-ubuntu-jre:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/runtime-quarkus-ubuntu-jre:root=docker-image://ghcr.io/yolean/runtime-quarkus-ubuntu-jre:root
    -
      name: Build and push runtime-quarkus-dev root
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: runtime-quarkus-dev
        tags: |
          ghcr.io/yolean/runtime-quarkus-dev:root
          ghcr.io/yolean/runtime-quarkus-dev:${{ github.sha }}-root
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/builder-quarkus=docker-image://ghcr.io/yolean/builder-quarkus
          yolean/runtime-quarkus-ubuntu:root=docker-image://ghcr.io/yolean/runtime-quarkus-ubuntu:root
    -
      name: Build and push runtime-quarkus-dev latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: to-nonroot/runtime-quarkus-dev
        tags: |
          ghcr.io/yolean/runtime-quarkus-dev:latest
          ghcr.io/yolean/runtime-quarkus-dev:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/runtime-quarkus-dev:root=docker-image://ghcr.io/yolean/runtime-quarkus-dev:root
