name: images

on:
  push:
    branches:
    - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    -
      uses: imjasonh/setup-crane@v0.1
    -
      run: >-
        crane cp          docker.io/yolean/kafka-keyvalue:7fa31f42731fc20a77988b478a3896732cc3dc88
          ghcr.io/${{ github.repository }}/kafka-keyvalue:7fa31f42731fc20a77988b478a3896732cc3dc88
        ;
