name: images

on:
  push:
    branches:
    - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    -
      uses: imjasonh/setup-crane@v0.3
    -
      run: |
        TAG_KKV=7fa31f42731fc20a77988b478a3896732cc3dc88
        crane cp docker.io/yolean/kafka-keyvalue:$TAG_KKV ghcr.io/yolean/kafka-keyvalue:$TAG_KKV
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    ### build steps below are generated ###
    -
      name: Build and push headless-chrome latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: headless-chrome
        tags: |
          ghcr.io/yolean/headless-chrome:latest
          ghcr.io/yolean/headless-chrome:${{ github.sha }}
        platforms: linux/amd64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-contexts: |
          yolean/docker-base=docker-image://ghcr.io/yolean/docker-base
    -
      name: Build and push git-http-readonly latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: git-http-readonly
        tags: |
          ghcr.io/yolean/git-http-readonly:latest
          ghcr.io/yolean/git-http-readonly:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push runtime-quarkus latest
      uses: docker/build-push-action@v5
      env:
        SOURCE_DATE_EPOCH: 0
      with:
        context: runtime-quarkus
        tags: |
          ghcr.io/yolean/runtime-quarkus:latest
          ghcr.io/yolean/runtime-quarkus:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
